name: job 1

on:
  push:
  pull_request:
    branches: 
      - main


defaults:
  run:
    working-directory: server

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm i
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint